[package]
name = "csharp-expr"
version = "0.1.0"
authors = ["Jêrome Rx <jerome+git@rouaix.eu>"]
edition = "2018"

[lib]
name="csharp_expr"
crate-type = ["dylib"]

[dependencies]
nom="5.0.1"
unescape = "0.1.0"
encoding_rs = "0.8.22"
once_cell = "1.3.0"

[dev-dependencies]
test-case = "0.3.3"

# [features]
# hello = ["regexp_macros"]