[package]
name = "csharp-expr"
version = "0.1.0"
authors = ["Jêrome Rx <jerome+git@rouaix.eu>"]
edition = "2018"

[lib]
name="csharp_expr"
crate-type = ["dylib"]

[dependencies]
nom="5.1.1"
unescape = "0.1.0"
encoding_rs = "0.8.22"
once_cell = "1.3.1"

[dev-dependencies]
test-case = "1.0.0"
