[package]
name = "csharp-expr"
version = "0.1.0"
authors = ["Jêrome Rx <jerome+git@rouaix.eu>"]
edition = "2018"

[lib]
name="csharp_expr"
crate-type = ["dylib"]

[dependencies]
nom="5.0.0"
unescape = "0.1.0"

[dev-dependencies]
test-case-derive = "0.2.1"

# [features]
# hello = ["regexp_macros"]